// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7bW8cWNY42flJeZ2aZUIdMVdQ9Dxk3dI',
    appId: '1:903880216410:web:a48038fb3d39837ae52d63',
    messagingSenderId: '903880216410',
    projectId: 'whatsapp-96042',
    authDomain: 'whatsapp-96042.firebaseapp.com',
    storageBucket: 'whatsapp-96042.appspot.com',
    measurementId: 'G-G5DEFJFSPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaROArswIhXW8Iw1QFi-Od1zbvXleBdl4',
    appId: '1:903880216410:android:6455119661a2f403e52d63',
    messagingSenderId: '903880216410',
    projectId: 'whatsapp-96042',
    storageBucket: 'whatsapp-96042.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdfaFvd79aJm-Thyq79DUxoB7jNPMAMuA',
    appId: '1:903880216410:ios:1b64cc890aae2238e52d63',
    messagingSenderId: '903880216410',
    projectId: 'whatsapp-96042',
    storageBucket: 'whatsapp-96042.appspot.com',
    iosClientId: '903880216410-mtjgbqvkb2hgpv1v9kg0pha67e4oie1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdfaFvd79aJm-Thyq79DUxoB7jNPMAMuA',
    appId: '1:903880216410:ios:5622f42983cf9767e52d63',
    messagingSenderId: '903880216410',
    projectId: 'whatsapp-96042',
    storageBucket: 'whatsapp-96042.appspot.com',
    iosClientId: '903880216410-rm546skg6k68g38ng0hf73s9tuebtrus.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone.RunnerTests',
  );
}
